### ISSUE TITLE
Warning Console

### ISSUE THREAD

**Issue by chemitaxis** [mkozhukharenko/mobx-form-validation#1]
Hi, first of all, thanks for sharing this code and post ;)

I have these warnings in console:

`warning.js:36 Warning: LoginForm: type specification of prop `form` is invalid; the type checker function must return `null` or an `Error` but returned a object. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).`

Ant this other:

`warning.js:36 Warning: Unknown prop `error` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

My question... why? Thanks! :)

**Comment by mkozhukharenko** [comment]
@chemitaxis you are welcome! 

Originally this code was written in TypeScript so I didn't pay too much attention to `PropTypes`. But now it's fixed )

thanks for submitting an issue.
